### ISSUE TITLE
lack of README.MD 

### ISSUE THREAD

**Issue by stone99** [status-im/murmur#16]
Is there any desc about this project? thanks!

**Comment by richard-ramos** [comment]
Hi @stone99!, thanks for your interest in this project.

I have updated it with a `README.md` containing details on what is the project, how to install it and run it. Bear in mind that even if this project already allows sending/receiving messges in whisper, it is still **HIGHLY EXPERIMENTAL** and under active development, and not recommended at all to be used for production purposes.

Cheers!
